# Generated by Django 4.0.3 on 2024-02-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0003_department_file_type_post_pdf_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='department',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
